import { addKeyword, EVENTS } from "@builderbot/bot";

export const iRemovalWindowsFlow = addKeyword(EVENTS.ACTION)
.addAnswer([
    '*🥰IREMOVAL🥰*',
    'Full señal en hello',
    '6S al X',
    '',
    'Descargar: https://iremovalpro.com/',
    'iRemoval PRO v7.2 (iRa1n v4.6)',
    'TUTORIAL: https://youtu.be/z08a0lWiQHw',
    '',
    'Pasos para activar:',
    '1. no está reportado en tu país',
    '2. Check https://imeipro.info/ que esté clean',
    '3. Realiza el jailbreak con iBypass LPro o checkra1n/palera1n.',
    '4. Haz clic en "Activate Device" hasta ver "Congratulations soportado".',
    '5. Registra el número de serie (SN). El registro es instantáneo, pero la activación puede tardar de 1 a 48 horas.',
    '6. Conéctate a Wi-Fi para FaceTime y notificaciones.',
    '7. Haz clic en "Activate Device" hasta ver "Successfully".',
    '8. *Activar SN en web o soporte* en https://dtodito-gsm.com',
    '9. ¡Listo!',
    '',
    'Compatibilidad iOS:',
    '6s/se = iOS 15.X',
    '7 y 7 plus = iOS 15.X',
    '8 y 8 plus = iOS 17.X',
    'X = iOS 17.X',
])
.addAnswer([
    '✅ Soporta iPhone 6s hasta iPhone X',
    '✅ Soporta iPad (2013 - 2018)',
    '✅ Soporta iOS & iPadOS desde la versión 12.0 en adelante',
    '✅ Soporta actualizaciones OTA (6s-X)',
    '✅ Compatible con Windows PC',
    '✅ Jailbreak integrado',
    '✅ Señal [COMPLETA]',
    '✅ Sin ataduras (Unthreted)',
    '✅ iCloud',
    '✅ FaceTime',
    '✅ iMessage',
    '✅ Notificaciones',
    '✅ Falso reinicio (Fake Reset)',
    '✅ Bloqueo de OTA',
])