import { addKeyword, EVENTS } from "@builderbot/bot";

export const opcion7rentaServerPrincipalesBoxFlow = addKeyword(EVENTS.ACTION)
    .addAnswer([
        'renta server de las principales box',
        '*ALQUILER 24/7*',
        '*1* EFT PRO',
        '*2* HYDRATOO',
        '*3* NCK BOX + UMT',
        '*4* BE NCK DONGLE + UMT',
        '*5* OCTOPLUS FRP',
        '*6* SIGMA BOX 3-4-5',
        '*7* Z3X SAM',
        '*8* Z3X SAM 2',
        '*9* EFT PRO',
        '*10* EFT PRO 2',
        '*11* HYDRA',
        '*12* NCK-UMT HORA QUITO',
        '*13* OCTO HUAWEI',
        '*14* OCTO LG',
        '*15* OCTO SAM',
        '*16* SIGMA PLUS',
        '*17* SIGMA PLUS',
        '*18* UMT-AVENGER-NCK HUAWEI',
        '*19* UMT-AVENGER-NCK HUAWEI S2',
        '*20* Z3X 1',
        '*21* Z3X 2',
        '*22* Z3X 3',
        '*23* vip halabtech✅',
    ])
    .addAnswer([
        '*🛠️ TOOLS EN RENTA (se alquilan por separado)*',
        '',
        '• Unlock Tools (6 horas)',
        '• Cheetah Tool (24 horas)',
        '• E-GSM (24 horas)',
        '• Chimera Pro',
        '• TR Tools',
        '• DFT Pro',
        '• MDMFix (6 horas)',
        '• RTC Tool (6 horas)',
        '• Android Multitool (2 horas)',
        '• CF Tools',
        '• DFT Pro (30 días)',
        '• DFT Pro (48 horas)',
        '• Griffin-Unlocker Tool (6 horas)',
        '• KG Killer Tool',
        '• MDMFix (30 días)',
        '• MDM Fix Tool (6 horas)',
        '• MobileSea Service Tool (MST)',
        '• Pandora Digital (15 días)',
        '• Pandora Digital (30 días)',
        '• Pandora Digital (48 horas)',
        '• PAPI Tool',
        '• Scorpion Tool',
        '• Server SHI/DT (15 días)',
        '• Server SHI/DT (48 horas)',
        '• SRS Tool (6 horas)',
        '• TFM Tool',
        '• UnlockTool.net (1 mes)',
        '',
        '🔁 Preguntar disponibilidad'
    ])